/**
 * V12 WEBHOOK SIGNATURE SCHEME — the contract upstream apps implement.
 *
 * Every ecosystem webhook carries a signature header:
 *
 *     V12-Signature: t=<unix_seconds>,v1=<hex_hmac_sha256>
 *
 * where the HMAC is computed over the exact string  `${t}.${rawBody}`  using
 * the shared per-app webhook secret (V12_<APP>_WEBHOOK_SECRET or the
 * V12_WEBHOOK_SECRET fallback). Verification is constant-time and rejects any
 * request whose timestamp is outside the tolerance window (replay protection).
 *
 * This is the same construction Stripe uses, so it's familiar to implement in
 * any language upstream apps are written in. Self-contained (node:crypto only).
 *
 * ── DO NOT EDIT THIS FILE ──────────────────────────────────────────────────
 * This is the shared contract, vendored VERBATIM into every V12 app — a
 * byte-identical copy exists in each one. There is a test asserting they match,
 * because a signature scheme that has quietly forked is the worst possible
 * thing to debug: both sides believe they are correct and nothing verifies.
 * Changes belong upstream, then get re-vendored everywhere at once.
 *
 * Adapters (secret resolution, header fallbacks, framework glue) go in
 * v12-webhook-adapter.ts — NOT here.
 */
import { createHmac, timingSafeEqual } from "node:crypto";

export const SIGNATURE_HEADER = "v12-signature";

export function signWebhook(secret: string, rawBody: string, timestampSec: number): string {
  const mac = createHmac("sha256", secret).update(`${timestampSec}.${rawBody}`).digest("hex");
  return `t=${timestampSec},v1=${mac}`;
}

export interface VerifyOptions {
  /** Max allowed clock skew in seconds (default 300 = 5 min). */
  toleranceSec?: number;
  /** Injectable clock for tests. */
  nowSec?: number;
}

export class WebhookError extends Error {
  constructor(public code: "MALFORMED" | "BAD_SIGNATURE" | "EXPIRED") {
    super(code);
  }
}

function parseHeader(header: string): { t: number; v1: string } {
  const parts = Object.fromEntries(
    header.split(",").map((kv) => kv.trim().split("=") as [string, string]),
  );
  const t = Number(parts.t);
  if (!Number.isFinite(t) || !parts.v1) throw new WebhookError("MALFORMED");
  return { t, v1: parts.v1 };
}

/** Verify a webhook signature; throws WebhookError on failure. Returns the timestamp. */
export function verifyWebhook(secret: string, rawBody: string, header: string, opts: VerifyOptions = {}): number {
  const { t, v1 } = parseHeader(header);
  const now = opts.nowSec ?? Math.floor(Date.now() / 1000);
  const tolerance = opts.toleranceSec ?? 300;
  if (Math.abs(now - t) > tolerance) throw new WebhookError("EXPIRED");
  const expected = createHmac("sha256", secret).update(`${t}.${rawBody}`).digest("hex");
  const a = Buffer.from(v1, "hex");
  const b = Buffer.from(expected, "hex");
  if (a.length !== b.length || !timingSafeEqual(a, b)) throw new WebhookError("BAD_SIGNATURE");
  return t;
}

/** Convenience for senders: build the { headers, body } to POST to a peer. */
export function buildSignedWebhook(secret: string, payload: unknown, nowSec?: number): { headers: Record<string, string>; body: string } {
  const body = JSON.stringify(payload);
  const t = nowSec ?? Math.floor(Date.now() / 1000);
  return {
    headers: { "content-type": "application/json", "V12-Signature": signWebhook(secret, body, t) },
    body,
  };
}
