import React, { useState, useMemo } from 'react';
import { ALL_BLOG_POSTS } from '../data/blogData';
import { BlogPost } from '../types';
import { motion, AnimatePresence } from 'framer-motion';
import { Calendar, Clock, User, ArrowRight, Sparkles, Loader2 } from 'lucide-react';
import { GoogleGenAI, Type } from "@google/genai";
import { cn } from '../lib/utils';

const BlogCard: React.FC<{ post: BlogPost }> = ({ post }) => {
  return (
    <motion.div 
      layout
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="glass-card group cursor-pointer overflow-hidden flex flex-col h-full"
    >
      <div className="relative aspect-video overflow-hidden">
        <img 
          src={post.image} 
          alt={post.title}
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
          referrerPolicy="no-referrer"
        />
        {/* Scanning Line Effect */}
        <motion.div 
          animate={{ y: ['-100%', '100%'] }}
          transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
          className="absolute inset-0 bg-gradient-to-b from-transparent via-v12-red/20 to-transparent h-1/2 pointer-events-none"
        />
        <div className="absolute top-4 left-4 bg-v12-red text-white px-3 py-1 text-[10px] font-black uppercase tracking-widest logo-glow">
          {post.category}
        </div>
      </div>
      
      <div className="p-8 flex flex-col flex-grow">
        <div className="flex items-center gap-4 text-[10px] font-bold text-v12-silver uppercase tracking-widest mb-4">
          <div className="flex items-center gap-1">
            <Calendar size={12} className="text-v12-red" />
            {post.date}
          </div>
          <div className="flex items-center gap-1">
            <Clock size={12} className="text-v12-red" />
            {post.readTime}
          </div>
        </div>

        <h4 className="text-2xl font-black uppercase tracking-tighter mb-4 group-hover:text-v12-red transition-colors leading-none">
          {post.title}
        </h4>
        
        <p className="text-sm text-v12-silver font-medium mb-8 line-clamp-2 uppercase leading-tight">
          {post.excerpt}
        </p>

        <div className="mt-auto flex items-center justify-between pt-6 border-t border-white/10">
          <div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest">
            <User size={14} className="text-v12-red" />
            {post.author}
          </div>
          <ArrowRight size={20} className="text-v12-red -translate-x-2 opacity-0 group-hover:translate-x-0 group-hover:opacity-100 transition-all" />
        </div>
      </div>
    </motion.div>
  );
};

export function BlogSection() {
  const [posts, setPosts] = useState<BlogPost[]>(ALL_BLOG_POSTS);
  const [filter, setFilter] = useState<'ALL' | 'V12News' | 'V12Media'>('ALL');
  const [isGenerating, setIsGenerating] = useState(false);

  const filteredPosts = useMemo(() => {
    if (filter === 'ALL') return posts.slice(0, 12);
    return posts.filter(p => p.category === filter).slice(0, 12);
  }, [posts, filter]);

  const generateAIPost = async () => {
    setIsGenerating(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: "Generate a short, punchy blog post title and excerpt for a multimedia agency called V12 Multimedia. The vibe is urban, high-tech, and aggressive.",
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              excerpt: { type: Type.STRING }
            },
            required: ["title", "excerpt"]
          }
        }
      });

      const data = JSON.parse(response.text || "{}");
      
      const newPost: BlogPost = {
        id: Date.now().toString(),
        title: data.title || "AI GENERATED INSIGHT",
        excerpt: data.excerpt || "Exploring the boundaries of digital creativity with V12's latest AI-driven workflows.",
        content: "Full content generated by AI...",
        category: 'V12News',
        date: new Date().toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' }).toUpperCase(),
        author: 'V12 AI',
        image: `https://picsum.photos/seed/${Date.now()}-digital-media-tech/800/450`,
        readTime: '3 MIN'
      };

      setPosts([newPost, ...posts]);
    } catch (error) {
      console.error("AI Generation failed:", error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <section id="blog" className="py-24 px-6 bg-v12-blue text-white border-t-4 border-white/10">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-20 gap-8">
          <div className="max-w-2xl">
            <div className="inline-block px-3 py-1 bg-v12-red text-white text-[10px] font-black uppercase tracking-[0.3em] mb-4 logo-glow">
              V12 INSIGHTS
            </div>
            <h3 className="text-5xl md:text-8xl font-black tracking-tighter leading-[0.85] uppercase">
              CREATIVE <br /> <span className="text-chrome">INTELLIGENCE</span>
            </h3>
            
            <div className="mt-8 flex flex-wrap gap-4">
              {['ALL', 'V12News', 'V12Media'].map((f) => (
                <button
                  key={f}
                  onClick={() => setFilter(f as any)}
                  className={cn(
                    "px-6 py-2 text-[10px] font-black uppercase tracking-widest border-2 transition-all",
                    filter === f 
                      ? "bg-v12-red border-v12-red text-white" 
                      : "border-white/10 text-v12-silver hover:border-v12-red hover:text-v12-red"
                  )}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>
          
          <div className="flex flex-col items-start md:items-end gap-4">
            <p className="text-v12-silver max-w-sm font-bold uppercase text-sm leading-tight md:text-right">
              Company updates, industry trends, and creative strategies from the front lines of urban multimedia.
            </p>
            <button 
              onClick={generateAIPost}
              disabled={isGenerating}
              className="btn btn-primary py-2 px-6 text-xs flex items-center gap-2 group"
            >
              {isGenerating ? (
                <Loader2 size={16} className="animate-spin" />
              ) : (
                <Sparkles size={16} className="group-hover:rotate-12 transition-transform" />
              )}
              {isGenerating ? 'GENERATING...' : 'GENERATE AI POST'}
            </button>
          </div>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          <AnimatePresence mode="popLayout">
            {filteredPosts.map((post) => (
              <BlogCard key={post.id} post={post} />
            ))}
          </AnimatePresence>
        </div>
        
        <div className="mt-16 text-center">
          <button className="btn btn-outline px-12 py-4 text-xs font-black uppercase tracking-widest">
            View All {filter === 'ALL' ? posts.length : posts.filter(p => p.category === filter).length} Articles
          </button>
        </div>
      </div>
    </section>
  );
}
